drop table if exists userkk cascade;

CREATE TABLE userkk
(
    id  int8 generated by default as identity unique,
    username varchar(200),
    name varchar(200),
    isEnabled boolean,
    keycloak_id varchar(200),
    company_id INTEGER,
    primary key (id)
);